using System;
using System.Collections.Generic;
using System.Text;

/***********************************************************************************
****作者：zhenggan；创建时间：2021/2/24 10:20:47；更新时间：
************************************************************************************/
namespace VirtualUniverse.Export.HtmlExport
{
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释
    /// summary
    /// 类 描 述：枚举Html节点类型
    /// /summary
    public enum EnumHtmlNodeType
    {
        /// <summary>
        /// 用户自定义标签
        /// </summary>
        UserDefine = 0,
        A = 1,
        Abbr = 2,
        Acronym = 3,
        Address = 4,
        Applet = 5,
        Area = 6,
        Article = 7,
        Aside = 8,
        Audio = 9,
        B = 10,
        Base = 11,
        Basefont = 12,
        Bdi = 13,
        Bdo = 14,
        Big = 15,
        Blockquote = 16,
        Body = 17,
        Br = 18,
        Button = 19,
        Canvas = 20,
        Caption = 21,
        Center = 22,
        Cite = 23,
        Code = 24,
        Col = 25,
        Colgroup = 26,
        Command = 27,
        Datalist = 28,
        Dd = 29,
        Del = 30,
        Details = 31,
        Dfn = 32,
        Dialog = 33,
        Dir = 34,
        Div = 35,
        Dl = 36,
        Dt = 37,
        Em = 38,
        Embed = 39,
        Fieldset = 40,
        Figcaption = 41,
        Figure = 42,
        Font = 43,
        Footer = 44,
        Form = 45,
        Frame = 46,
        Frameset = 47,
        Head = 48,
        Header = 49,
        Hgroup = 50,
        H1 = 51,
        H2 = 52,
        H3 = 53,
        H4 = 54,
        H5 = 55,
        H6 = 56,
        Hr = 57,
        I = 58,
        Iframe = 59,
        Img = 60,
        Input = 61,
        Ins = 62,
        Kbd = 63,
        Keygen = 64,
        Label = 65,
        Legend = 66,
        Li = 67,
        Link = 68,
        Main = 69,
        Map = 70,
        Mark = 71,
        Menu = 72,
        Meta = 73,
        Meter = 74,
        Nav = 75,
        Noframes = 76,
        Noscript = 77,
        Object = 78,
        Ol = 79,
        Optgroup = 80,
        Option = 81,
        Output = 82,
        P = 83,
        Param = 84,
        Pre = 85,
        Html = 86,
        Picture = 87,
        Progress = 88,
        Q = 89,
        Rp = 90,
        Rt = 91,
        Ruby = 92,
        S = 93,
        Samp = 94,
        Script = 95,
        Section = 96,
        Select = 97,
        Small = 98,
        Source = 99,
        Span = 100,
        Strike = 101,
        Strong = 102,
        Style = 103,
        Sub = 104,
        Summary = 105,
        Sup = 106,
        Table = 107,
        Tbody = 108,
        Td = 109,
        Textarea = 110,
        Tfoot = 111,
        Th = 112,
        Thead = 113,
        Time = 114,
        Title = 115,
        Tr = 116,
        Track = 117,
        Tt = 118,
        U = 119,
        Ul = 120,
        Var = 121,
        Video = 122,
        Wbr = 123
    }
}
